name: futurospossiveis2022
recipe: drupal9
config:
  webroot: web
proxy:  
  appserver:    
    - futurospossiveis2022.lndo.site    
services:
  futurospossiveis2022:
    type: mysql:5.7    
    creds:      
      user: drupal9      
      password: drupal9      
      database: futurospossiveis