features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
meta_titulo: ''
meta_descricao: 'Festival Futuros Possíveis 2022'
meta_image: {  }
