_core:
  default_config_hash: SMMHLGfy4YoZHXabFVqh8vjsvM_MzWgohArG_gXaIXQ
langcode: pt-br
mail_login_enabled: 1
mail_login_override_login_labels: 1
mail_login_username_title: 'Login por email'
mail_login_username_description: 'You can use your username or email address to login.'
